services:
  - type: web
    name: anime-forum-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"  # or whatever your entry point is
    envVars:
      - key: DATABASE_URL
        value: YOUR_POSTGRES_URL   # from Railway/ElephantSQL/etc.
      - key: SECRET_KEY
        value: your-super-secret-key
